"""ptz -- hardware-independent logical PTZ model (Phase 2).

Stable application-level contract between the PTZ UI/controller and
the future OPC UA client / PLC mapping / simulator. No OPC UA, no
Siemens, no simulator, no GUI imports anywhere in this package.
"""

from thermal_monitor.ptz.errors import (
    PtzError,
    PtzErrorCategory,
    PtzStateError,
    PtzValidationError,
)
from thermal_monitor.ptz.mapping import (
    LogicalField,
    NodeAccess,
    NodeDataType,
    PtzMapping,
    PtzMappingError,
    SiemensPtzMapping,
    SimulatorPtzMapping,
)
from thermal_monitor.ptz.protocol import (
    EventCallback,
    OpcUaNodeError,
    OpcUaTimeoutError,
    OpcUaTransport,
    OpcUaTransportError,
    PtzNodeDescriptor,
    SubscriptionHandle,
    TransportEvent,
    ValueCallback,
)
from thermal_monitor.ptz.client import (
    AsyncuaTransport,
    ConnectionCallback,
    OpcUaClientConfig,
    OpcUaSecurity,
    OpcUaSession,
    coerce_bool,
    coerce_float,
    command_to_fields,
    translate_error,
)
from thermal_monitor.ptz.controller import (
    CommandStrobe,
    PtzCommandError,
    PtzController,
    PtzOperation,
    PtzOperationState,
)
from thermal_monitor.ptz.diagnostics import (
    DiagnosticCheck,
    DiagnosticsReport,
    run_movement_checks,
    run_read_only_checks,
)
from thermal_monitor.ptz.retarget import ObserverRetargetCoordinator
from thermal_monitor.ptz.roi_activation import (
    ActivePositionContext,
    ActivePositionRegistry,
    RoiActivationResult,
    RoiActivationState,
    RoiActivationWorkflow,
)
from thermal_monitor.ptz.service import (
    PtzService,
    PtzServiceConfig,
    StatusListener,
)
from thermal_monitor.ptz.models import (
    MoveMode,
    PtzCommand,
    PtzLimits,
    PtzStationBinding,
    PtzTolerance,
    VelocityMode,
    within_tolerance,
)
from thermal_monitor.ptz.positions import (
    PtzPosition,
    check_position_binding,
    generate_position_id,
)
from thermal_monitor.ptz.positions_io import (
    ConflictPolicy,
    FORMAT_TYPE,
    FORMAT_VERSION,
    ImportPreview,
    ImportResult,
    commit_import,
    export_positions,
    preview_import,
)
from thermal_monitor.ptz.siemens import (
    ProfileStatus,
    REQUIRED_SIEMENS_FIELDS,
    SIEMENS_MAPPING_DOCUMENT_VERSION,
    SiemensMappingDocument,
    mapping_for_profile,
    validate_profile,
    verify_siemens_document,
)
from thermal_monitor.ptz.station import (
    build_service,
    build_service_config,
    merge_limits,
    resolve_binding,
    resolve_endpoint,
)
from thermal_monitor.ptz.state import (
    CalibrationState,
    PlcConnectionState,
    PtzMovementState,
    PtzStatus,
    allowed_movement_transition,
    allowed_plc_transition,
    check_movement_transition,
    check_plc_transition,
)

__all__ = [
    "ActivePositionContext",
    "ActivePositionRegistry",
    "AsyncuaTransport",
    "CalibrationState",
    "CommandStrobe",
    "ConflictPolicy",
    "ConnectionCallback",
    "DiagnosticCheck",
    "DiagnosticsReport",
    "EventCallback",
    "FORMAT_TYPE",
    "FORMAT_VERSION",
    "ImportPreview",
    "ImportResult",
    "LogicalField",
    "MoveMode",
    "NodeAccess",
    "NodeDataType",
    "OpcUaClientConfig",
    "OpcUaNodeError",
    "OpcUaSecurity",
    "OpcUaSession",
    "OpcUaTimeoutError",
    "OpcUaTransport",
    "OpcUaTransportError",
    "ObserverRetargetCoordinator",
    "PlcConnectionState",
    "ProfileStatus",    "PtzCommand",
    "PtzCommandError",
    "PtzController",    "PtzError",
    "PtzErrorCategory",
    "PtzLimits",
    "PtzMapping",
    "PtzMappingError",
    "PtzMovementState",
    "PtzOperation",
    "PtzOperationState",
    "PtzPosition",
    "PtzService",
    "PtzServiceConfig",
    "PtzStateError",
    "PtzStationBinding",
    "PtzStatus",
    "PtzTolerance",
    "PtzValidationError",
    "PtzNodeDescriptor",
    "REQUIRED_SIEMENS_FIELDS",
    "RoiActivationResult",
    "RoiActivationState",
    "RoiActivationWorkflow",
    "SIEMENS_MAPPING_DOCUMENT_VERSION",
    "SiemensMappingDocument",
    "SiemensPtzMapping",
    "SimulatorPtzMapping",
    "StatusListener",
    "SubscriptionHandle",
    "TransportEvent",
    "ValueCallback",
    "VelocityMode",
    "allowed_movement_transition",
    "allowed_plc_transition",
    "build_service",
    "build_service_config",
    "check_movement_transition",
    "check_plc_transition",
    "coerce_bool",
    "coerce_float",
    "command_to_fields",
    "commit_import",
    "export_positions",
    "generate_position_id",
    "mapping_for_profile",
    "merge_limits",
    "preview_import",
    "resolve_binding",
    "resolve_endpoint",
    "run_movement_checks",
    "run_read_only_checks",
    "translate_error",
    "validate_profile",
    "verify_siemens_document",
    "within_tolerance",
]
