"""
TMS V3 Configuration Package.

Provides centralized configuration management with external YAML configuration,
environment variable overrides, and path resolution for deployment scenarios.
"""

from thermal_monitor.config.manager import (
    ConfigurationManager,
    ConfigurationError,
    create_config_manager,
)
from thermal_monitor.config.models import (
    AppConfig,
    ApplicationConfig,
    DatabaseConfig,
    CamerasConfig,
    CameraAcquisitionConfig,
    CameraRecoveryConfig,
    CameraConnectionConfig,
    CameraDiscoveryConfig,
    CameraStartupConfig,
    CameraMappingConfig,
    SystemConfig,
    StorageConfig,
    RecordingConfig,
    CalibrationConfig,
    ProcessingConfig,
    AlarmsConfig,
    PTZConfig,
    PTZLimitsConfig,
    PTZDefaultPositionConfig,
    PTZSpeedsConfig,
    ROIConfig,
    ROIDefaultsConfig,
    OfflineConfig,
    OfflinePlaybackConfig,
    LoggingConfig,
    UIConfig,
    UIColorsConfig,
    UIWindowsConfig,
    UILiveConfig,
    UIDisplayConfig,
    NetworkConfig,
    HALCONConfig,
)

__all__ = [
    # Manager
    "ConfigurationManager",
    "ConfigurationError",
    "create_config_manager",
    # Models
    "AppConfig",
    "ApplicationConfig",
    "DatabaseConfig",
    "CamerasConfig",
    "CameraAcquisitionConfig",
    "CameraRecoveryConfig",
    "CameraConnectionConfig",
    "CameraDiscoveryConfig",
    "CameraStartupConfig",
    "CameraMappingConfig",
    "SystemConfig",
    "StorageConfig",
    "RecordingConfig",
    "CalibrationConfig",
    "ProcessingConfig",
    "AlarmsConfig",
    "PTZConfig",
    "PTZLimitsConfig",
    "PTZDefaultPositionConfig",
    "PTZSpeedsConfig",
    "ROIConfig",
    "ROIDefaultsConfig",
    "OfflineConfig",
    "OfflinePlaybackConfig",
    "LoggingConfig",
    "UIConfig",
    "UIColorsConfig",
    "UIWindowsConfig",
    "UILiveConfig",
    "UIDisplayConfig",
    "NetworkConfig",
    "HALCONConfig",
]